# my config
version: 2.1
orbs:
  node: circleci/node@3.0.0
  docker: circleci/docker@1.4.0

workflows:
  node-tests:
    jobs:
      - node/test
      # uncomment the 3 following lines to enable deploying
      # - deploy:
      #     requires:
      #       - build-and-push
